apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fitness-app
  template:
    metadata:
      labels:
        app: fitness-app
    spec:
      containers:
        - name: fitness-app
          image: fitnessregistry.azurecr.io/fitness-app:latest
          ports:
            - containerPort: 8000